### PR TITLE
feat(*): add `testing=true` for resty cli testing

### PR DESCRIPTION
**Pull request by chronolaw**
See KAG-930

### CODE REVIEW

**Comment by dndx** [comment]
If I read the change correctly, when `listening=off`, this only works inside a single worker correct?

In that case, we can consider call it `testing=true` instead.

**Comment by chronolaw** [comment]
> If I read the change correctly, when `listening=off`, this only works inside a single worker correct?
> 
> In that case, we can consider call it `testing=true` instead.

@bungle , what do you think?

**Comment by bungle** [comment]
@chronolaw could this run the event right when it arrived? Now I need to add `ngx.sleeps` to actually execute the callbacks.

**Comment by chronolaw** [comment]
> @chronolaw could this run the event right when it arrived? Now I need to add `ngx.sleeps` to actually execute the callbacks.

Sure. If `testing=true` then the library will fall back to local events propagation, which means events will be processed immediately.

**Review by bungle — APPROVED** [review]

**Pull request merged**
